package org.thecircle.seabattleclientapi;

public enum ServerResponse {
    WON,
    LOST,
    HIT,
    HIT_AND_SUNK,
    MISSED,
    ALREADY_SHOT,
    WRONG_LOGIN,
    MISSING_GAME,
    SUCCESS,
    GAME_ALREADY_EXISTS,
    NOT_YOUR_TURN,
    GAME_NOT_STARTED,
    GAME_ALREADY_STARTED,
    GAME_FINISHED,
    OVERLAPPING_SHIPS,
    INVALID_SHIPS,
    INVALID_PLAYER,
    INVALID_COORDINATE,
    INVALID_RULES,
    BLANK_PASSWORD,
    PLAYER_ALREADY_EXISTS,
    PERMISSION_DENIED,
    ERROR
}
